### PR TITLE
Daggett County - parse pdf data into csv

### PR DESCRIPTION
**Pull request by teacupwoozy**
I'll wait to hear if this all looks okay before I start on another county. thanks!

### CODE REVIEW

**Comment by dwillis** [comment]
@teacupwoozy thanks! just a couple of things:

1. header column names are all lower case, so `county`, etc.
2. For races that have districts (like State Senate and U.S. House), the `district` column should get the number of the district. So for "STATE SENATOR D26" it would be "26"

**Comment by dwillis** [comment]
@teacupwoozy awesome - only thing I missed was you can remove the D from the district values, so just the number remains.

**Comment by teacupwoozy** [comment]
@dwillis should be good now!

**Comment by dwillis** [comment]
@teacupwoozy Thanks!

**Pull request merged**
